### ISSUE TITLE
add `__cuda` to run section

### ISSUE THREAD

**Issue by ngam** [conda-forge/cudatoolkit-feedstock#78] opened 2022-05-27 16:47 UTC

**Comment by leofang** [comment] 2022-05-27 23:00
I don't think it's correct. There are desire to be able to install CUDA packages on systems without GPU (or CUDA driver), for example when compiling packages in a CI. If you set `__cuda` to `run`, these use cases would fail.

**Comment by ngam** [comment] 2022-05-27 23:05
> I don't think it's correct. There are desire to be able to install CUDA packages on systems without GPU (or CUDA driver), for example when compiling packages in a CI. If you set `__cuda` to `run`, these use cases would fail.

That could be overridden with `CONDA_OVERRIDE_CUDA`. I am just following the policy being set in tensorflow and pytorch. It is better to set the `__cuda` constraint here, rather than those packages imo.

**Comment by ngam** [comment] 2022-05-27 23:22
See my documentation here: https://conda-forge.org/docs/user/tipsandtricks.html#installing-cuda-enabled-packages-like-tensorflow-and-pytorch

**Comment by ngam** [comment] 2022-05-27 23:23
The simple idea is that we want big packages (big because of cudatoolkit btw) to only install on computers with GPUs, unless the user explicitly desires otherwise (via override).

In cudatoolkit, there is a "run constraint", we want a run condition

**Comment by leofang** [comment] 2022-05-27 23:24
(Copied from my comment elsewhere) If you just need a mechanism to deprioritize a certain build kind, couldn't you just use the build-number trick that already works for MPI? https://conda-forge.org/docs/maintainer/knowledge_base.html#preferring-a-provider-usually-nompi

**Comment by ngam** [comment] 2022-05-27 23:25
> (Copied from my comment elsewhere) If you just need a mechanism to deprioritize a certain build kind, couldn't you just use the build-number trick that already works for MPI? https://conda-forge.org/docs/maintainer/knowledge_base.html#preferring-a-provider-usually-nompi

That's a good idea. The current implementation is to be even more strict than just deprioritization. Something to consider definitely...

**Comment by leofang** [comment] 2022-05-27 23:27
I am not in favor of multiple approaches being adopted in conda-forge on deciding the package priority. The MPI one has a much longer history and it works fine. TF and Torch being newcomers to the CF ecosystem should respect that IMHO.

**Comment by leofang** [comment] 2022-05-27 23:28
(It goes without saying that my assumption here is "if it also works for CUDA", but I can't think of any reason it wouldn't 🙂)

**Comment by leofang** [comment] 2022-05-28 00:13
cc: @m3vaz for vis

**Comment by ngam** [comment] 2022-05-28 00:35
> I am not in favor of multiple approaches being adopted in conda-forge on deciding the package priority. The MPI one has a much longer history and it works fine. TF and Torch being newcomers to the CF ecosystem should respect that IMHO.

Arguably, the issue of cuda vs no cuda is definitely more of a virtual package issue as per design. The `__cuda` designation is there for this very reason.

Again though, this change wasn't my personal preference! I argued at length against it, but the majority decision was to go for this restriction. It makes my life harder because I have to set up my cuda environments on a login node with no GPU and the compute nodes with the GPUs have no internet.

Anyway, I am not necessarily arguing for one thing vs another, I am just saying, if we are gonna add `__cuda` in the run section, we should add it to the source of the issue (cudatoolkit, nccl, cudnn, etc.) and not in places like tensorflow, pytorch, and jax.

**Comment by m3vaz** [comment] 2022-05-28 05:33
The issue is marked as a question. I wasn't able to find a clear question above, but it seems like it centers around "Can `__cuda` be set as a run requirement instead of a run_constrained?"

Trying to summarize my understanding of the context and then some comments:
TF and PyTorch sometimes installed (either accidentally or because it got prioritized) the gpu-enabled packages  to users' machines. The gpu-enabled packages have a dependency on cudatoolkit. The portion of the userbase which does not not have a gpu on their current system, do not need the gpu-enabled packages, and so downloading the entire cudatoolkit is not necessary. 

By adding a hard `__cuda` run requirement, TF and PyTorch avoid this issue, because the gpu packages are only downloaded where gpu's have been set up (or users explicitly override the cuda virtual package) and non-gpu users now only ever need to deal with the cpu-only package. 

While I follow the above, I'm not sure how that then becomes this:
> if we are gonna add `__cuda` in the run section, we should add it to the source of the issue

To demonstrate the issues at hand, I'm going to focus a moment into the use case that @leofang raised, building.

1) What issue are you trying to solve here?

This sounds like an xy problem. As @leofang already pointed out, it sounds like what you're actually looking for is a way to make gpu-packages not selected *by default*. Moving `__cuda` to the run requirements for cudatoolkit goes beyond that. 

First, for the dependent packages you've mentioned (jax, tensorflow, pytorch), there are effectively two types of packages, cpu+gpu and cpu-only. It makes sense that `__cuda` can be added to to the run requirements because there are cpu-only alternative packages (feel free to correct me if I'm wrong here).  Additionally, since there is no situation where the gpu bits would be used on a system without a gpu, the gpu bits should only be pulled when they will be used. For cudatoolkit, there is no cpu-only package (and conceptually what that would mean isn't exactly clear) and the bits have a clear use case (building) even if no gpu is present.

Second, what happens to the packages that depend on cudatoolkit that don't produce a standalone cpu-only package right now? Adding a `__cuda` run requirement means that they would be effectively locked at the current version of cudatoolkit until they updated their recipes and refactored their code to build a cpu-only package.

2) Does the override variable always work as intended?

From the link you pointed to in the user documentation and the context provided, your focus is on users who can control the specifics of their environment. cudatoolkit is pulled into environments where there may be controls against manipulating the  environment, or where changing the environment is not intended usage. cf is an example of this. For conda-forge, maintainers are primarily intended to interact with their recipe, and building is sandboxed in environments that are maintained centrally. It's not a typical use case for maintainers to be modifying the build scripts nor editing the build environment variables. Maintainers could manually set the CUDA override variable, but those changes would just get wiped out at the next PR when files are re-rendered. 

Additionally, relying on environment variables can generally make builds difficult to reproduce since now reproducers need to have both the recipe and the environment. Relying on environment variables can also lead to unintended side-effects, since changes to the environment can also introduce subtle changes to the build (e.g. package hashes).

My point:
All of this is to say that TF and PyTorch's approach to the issue is perfectly fine, however applying the same patch to cudatoolkit may not translate well.

**Comment by ngam** [comment] 2022-05-28 15:33
> The issue is marked as a question. I wasn't able to find a clear question above, but it seems like it centers around "Can `__cuda` be set as a run requirement instead of a run_constrained?"

More like a suggestion. To mark adding `__cuda` here as an alternative to adding it in downstream recipes.


>My point:
All of this is to say that TF and PyTorch's approach to the issue is perfectly fine, however applying the same patch to cudatoolkit may not translate well.

Overall, your understanding and analysis are correct. And your point is well taken. Let me address the two main concerns below.

> Second, what happens to the packages that depend on cudatoolkit that don't produce a standalone cpu-only package right now? Adding a `__cuda` run requirement means that they would be effectively locked at the current version of cudatoolkit until they updated their recipes and refactored their code to build a cpu-only package.

Good point, not sure if there are packages like that around. Maybe there are. But there is no "locked out" --- you can always override it.



> 2\. Does the override variable always work as intended?
> 
> From the link you pointed to in the user documentation and the context provided, your focus is on users who can control the specifics of their environment. cudatoolkit is pulled into environments where there may be controls against manipulating the environment, or where changing the environment is not intended usage. cf is an example of this. For conda-forge, maintainers are primarily intended to interact with their recipe, and building is sandboxed in environments that are maintained centrally. It's not a typical use case for maintainers to be modifying the build scripts nor editing the build environment variables. Maintainers could manually set the CUDA override variable, but those changes would just get wiped out at the next PR when files are re-rendered.
> 
> Additionally, relying on environment variables can generally make builds difficult to reproduce since now reproducers need to have both the recipe and the environment. Relying on environment variables can also lead to unintended side-effects, since changes to the environment can also introduce subtle changes to the build (e.g. package hashes).

Please don't worry about building --- this issue only matters for users downloading and installing packages. For building, we already have a custom docker image where `__cuda` is in fact set (hence, overriding). There would never be a case where a maintainer will need to set the override variable in their recipe. In fact, your argument makes the point for enabling it here rather than downstream because some packages may pull cudatoolkit directly (rather than `compile('cuda')`) and that may be improper, so having this run condition here fills the point.

Reminder: I am not here arguing for adding `__cuda` in general; I am just arguing that if we are going to add it, we should be adding it here. And I am obviously not a maintainer and I am not going to force you to do this, I am just suggesting this is the place to adopt this solution. I could be wrong (as you and leo think) and maybe this issue needs to be elevated for the core team to decide an appropriate solution ecosystem-wide or continue with the ad hoc solution per recipe.

**Comment by ngam** [comment] 2022-05-28 15:37
Should I open this issue in the main repo for the core team to discuss and then come back here? I will link to your argument.

**Comment by ngam** [comment] 2022-05-28 15:53
Fwiw, I like leo's solution much more than the `__cuda` condition. Maybe that could be proposed as an alternative for the core team. I will think a little more about it.

**Closed** 2022-06-02 05:14 UTC
Labels: question

**Comment by jakirkham** [comment] 2022-06-02 06:03
It's probably worth reading issue ( https://github.com/conda/conda/issues/9115 ) for more background on why this was decided upon
